# Generated by Django 6.0 on 2025-12-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeresource',
            name='region',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('EU', 'Europe'), ('APAC', 'Asia-Pacific'), ('NA', 'North America'), ('SA', 'South America')], default='GLOBAL', max_length=20),
        ),
    ]
