# Generated by Django 6.0 on 2025-12-23 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_alter_knowledgeresource_status_aiflag_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeresource',
            name='current_stage',
            field=models.CharField(choices=[('CHAMPION', 'Knowledge Champion'), ('REGIONAL_OFFICER', 'Regional Officer'), ('GOV_COUNCIL', 'Knowledge Governance Council')], default='CHAMPION', max_length=30),
        ),
        migrations.AddField(
            model_name='knowledgeresource',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReviewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('CHAMPION', 'Knowledge Champion'), ('REGIONAL_OFFICER', 'Regional Officer'), ('GOV_COUNCIL', 'Knowledge Governance Council')], max_length=30)),
                ('decision', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('CHANGES_REQUESTED', 'Changes Requested')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_steps', to='knowledge.knowledgeresource')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_steps_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
