# Generated by Django 6.0 on 2025-12-24 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_knowledgeresource_current_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewstep',
            options={},
        ),
        migrations.RemoveField(
            model_name='knowledgeresource',
            name='file',
        ),
        migrations.AlterField(
            model_name='reviewstep',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_steps_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KnowledgeResourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='knowledge_resources/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_versions_created', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgeresource')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('resource', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='knowledgeresource',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgeresourceversion'),
        ),
        migrations.AddField(
            model_name='reviewstep',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_steps', to='knowledge.knowledgeresourceversion'),
        ),
    ]
