# Generated by Django 6.0 on 2025-12-24 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_alter_reviewstep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiflag',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_flags', to='knowledge.knowledgeresourceversion'),
        ),
    ]
