# Generated by Django 6.0 on 2025-12-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_aiflag_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeresource',
            name='submitted_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgeresourceversion'),
        ),
    ]
