# Generated by Django 6.0 on 2026-01-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_knowledgeresource_submitted_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewstep',
            name='decision',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('CHANGES_REQUESTED', 'Changes Requested'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], max_length=30),
        ),
    ]
