# Generated by Django 6.0 on 2026-01-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_alter_reviewstep_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeresource',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=20),
        ),
    ]
