# Generated by Django 6.0 on 2025-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CHAMPION', 'Knowledge Champion'), ('OFFICER', 'Regional Officer'), ('COUNCIL', 'Government Council'), ('ADMIN', 'System Admin')], default='EMPLOYEE', max_length=20),
        ),
    ]
