# Generated by Django 6.0 on 2026-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('GLOBAL', 'Global'), ('EU', 'Europe'), ('APAC', 'Asia-Pacific'), ('NA', 'North America'), ('SA', 'South America')], max_length=20, null=True),
        ),
    ]
